services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "uzyO776eNVLjVY8SkGEZ"
      POSTGRES_DB: "database"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=$$POSTGRES_USER --dbname=$$POSTGRES_DB"]
      interval: 1s
      timeout: 2s
      retries: 10

  redis:
    image: cgr.dev/chainguard/redis:latest
    ports:
      - "6379:6379"
    command: ["--requirepass", "JKaGOI0JO9zU4BPv5xID"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 10

  backend:
    build:
      context: ./dev/backend
      dockerfile: Dockerfile.dev
    tty: true
    env_file: ./dev/backend/.env
    environment:
      PYTHONUNBUFFERED: 1
      ORIGIN_URL: "http://localhost"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    # Commented out for faster startup
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
    #   interval: 30s
    #   timeout: 2s
    #   retries: 2
    develop:
      watch:
        - action: sync
          path: ./dev/backend/app
          target: /app
        - action: rebuild
          path: ./dev/backend/uv.lock

  frontend:
    build:
      context: ./dev/frontend
      dockerfile: Dockerfile.dev
    environment:
      BACKEND_CONTAINER_URL: "http://backend:8000"
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
    restart: on-failure
    develop:
      watch:
        - action: sync
          path: ./dev/frontend/app
          target: /app/app
        - action: rebuild
          path: ./dev/frontend/pnpm-lock.yaml

volumes:
  postgres_data: