version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: "./backend/.env"
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: