name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        python -m pip install --upgrade pip
        pip install uv

    - name: Setup uv environment
      run: |
        cd ./dev/backend
        uv venv
        uv lock
        uv sync
        source .venv/bin/activate

    - name: Analysing the code with pylint
      working-directory: dev/backend
      run: |
        pylint --rcfile=.pylintrc $(git ls-files '*.py')
